CREATE DATABASE SSOLVE_DATABASE;

USE SSOLVE_DATABASE;

CREATE TABLE CLIENTES_EMPRESAS(
	ID INT IDENTITY PRIMARY KEY 
	,NOME VARCHAR(255) NOT NULL UNIQUE
	,CNPJ CHAR(6) NOT NULL UNIQUE
	,RAZAO_SOCIAL VARCHAR(255) NOT NULL
	,ENDERECO VARCHAR(255) NOT NULL
);

CREATE TABLE LOCAIS_EMPRESAS(
	ID INT IDENTITY PRIMARY KEY 
	,NOME_LOCAL VARCHAR(255) NOT NULL
);

CREATE TABLE ITEM(
	ID INT IDENTITY PRIMARY KEY 
	,TIPO_DE_SERVICO VARCHAR(255) NOT NULL
	,PRECO INT NOT NULL--FLOAT
);
 
CREATE TABLE FUNCIONARIOS(
	ID INT IDENTITY PRIMARY KEY 
	,NOME VARCHAR(255) NOT NULL
);

CREATE TABLE SERVICOS_PRESTADOS(
	ID INT IDENTITY PRIMARY KEY
	,ID_EMPRESA INT FOREIGN KEY REFERENCES CLIENTES_EMPRESAS(ID) -- ADDED
	,ID_ITEM INT FOREIGN KEY REFERENCES ITEM(ID)
	,ID_LOCAL INT FOREIGN KEY REFERENCES LOCAIS_EMPRESAS(ID)
	,DATA_HORA_INICIO DATETIME NOT NULL
	,DATA_HORA_FINAL DATETIME
);

CREATE TABLE SERVICOS_FUNCIONARIOS(
	ID_SERVICO INT FOREIGN KEY REFERENCES SERVICOS_PRESTADOS(ID)
	,ID_FUNCIONARIO INT FOREIGN KEY REFERENCES FUNCIONARIOS(ID)
);