CREATE DATABASE SSOLVE_DATABASE; --CRIA O BANCO DE DADOS 'SSOLVE_DATABASE'

USE SSOLVE_DATABASE; --UTILIZA O BANCO DE DADOS 'SSOLVE_DATABASE'

--CRIA A TABELA 'CLIENTES/EMPRESAS'
CREATE TABLE CLIENTES_EMPRESAS(
	ID INT IDENTITY PRIMARY KEY
	,NOME VARCHAR(255) NOT NULL UNIQUE
	,CNPJ CHAR(6) NOT NULL UNIQUE
	,RAZAO_SOCIAL VARCHAR(255) NOT NULL
	,ENDERECO VARCHAR(255) NOT NULL
);

--CRIA A TABELA PARA GUARDAR OS POSSIVEIS LOCAIS DA EMPRESA
CREATE TABLE LOCAIS_EMPRESAS(
	ID INT IDENTITY PRIMARY KEY 
	,NOME_LOCAL VARCHAR(255) NOT NULL
);

--CRIA A TABELA PARA OS ITENS QUE PODEM SER UTILIZADOS NOS SERVICOS
CREATE TABLE ITEM(
	ID INT IDENTITY PRIMARY KEY 
	,TIPO_DE_SERVICO VARCHAR(255) NOT NULL
	,PRECO INT NOT NULL--FLOAT
);

--ALTERA A TABELA ITEM PARA REMOVER A COLUNA 'TIPO_DE_SERVICO'
ALTER TABLE ITEM
	DROP COLUMN TIPO_DE_SERVICO

--ALTERA A TABELA ITEM PARA ADICIONAR A COLUNA 'TIPO_DE_ITEM'
ALTER TABLE ITEM
	ADD TIPO_DE_ITEM VARCHAR(255) NOT NULL UNIQUE

--CRIA A TABELA DOS POSSIVEIS SERVICOS, COMO MANUTENCAO, INSTALACAO E TROCA.
CREATE TABLE SERVICOS(
	ID INT IDENTITY PRIMARY KEY
	,TIPO_DE_SERVICO VARCHAR(255) NOT NULL UNIQUE
);

--CRIA A TABELA DE FUNCIONARIOS
CREATE TABLE FUNCIONARIOS(
	ID INT IDENTITY PRIMARY KEY 
	,NOME VARCHAR(255) NOT NULL
);

--CRIA A TABELA DE SERVICOS PRESTADOS PELA EMPRESA SSOLVE
CREATE TABLE SERVICOS_PRESTADOS(
	ID INT IDENTITY PRIMARY KEY
	,ID_EMPRESA INT FOREIGN KEY REFERENCES CLIENTES_EMPRESAS(ID) -- ADDED
	,ID_ITEM INT FOREIGN KEY REFERENCES ITEM(ID)
	,ID_LOCAL INT FOREIGN KEY REFERENCES LOCAIS_EMPRESAS(ID)
	,DATA_HORA_INICIO DATETIME NOT NULL
	,DATA_HORA_FINAL DATETIME
);

--ALTERA A TABELA SERVICOS PRESTADOS PARA ADICIONAR A COLUNA 'ID_SERVICO'
ALTER TABLE SERVICOS_PRESTADOS
	ADD ID_SERVICO INT FOREIGN KEY REFERENCES SERVICOS(ID)

--CRIA A TABELA INTERMEDIARIA PARA RELACIONAR OS FUNCIONARIOS COM O SERVICO PRESTADO
CREATE TABLE SERVICOS_FUNCIONARIOS(
	ID_SERVICO INT FOREIGN KEY REFERENCES SERVICOS_PRESTADOS(ID)
	,ID_FUNCIONARIO INT FOREIGN KEY REFERENCES FUNCIONARIOS(ID)
);